FROM apache/spark:3.5.1

USER root

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget -P /opt/spark/jars/ \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    wget -P /opt/spark/jars/ \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.367/aws-java-sdk-bundle-1.12.367.jar

RUN mkdir -p /jobs && \
    chmod -R 777 /jobs

RUN mkdir -p /tmp/.ivy2 && \
    chmod -R 777 /tmp/.ivy2

#
ENV USER=spark

ENV SPARK_SUBMIT_OPTS="-Divy.home=/tmp/.ivy2 -Divy.cache.dir=/tmp/.ivy2"

WORKDIR /jobs